### ISSUE TITLE
plugin visu_websocket: extend protocol to enable cancellation of time series abonnement

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/plugins#291]
visu_websocket extend protocol to enable cancellation of time series abonnement

**Comment by msinn** [comment]
How would the driver in smartVISU cancel a series and how would this functionality be used in smartVISU?

**Comment by bmxp** [comment]
Have a look at [this post](https://knx-user-forum.de/forum/supportforen/smartvisu/1248054-highstock-chart-für-charts-in-schick?p=1420799#post1420799) in knxuf

**Comment by bmxp** [comment]
Maybe we should also think about using threads for retrieving data, see [this post](https://knx-user-forum.de/forum/supportforen/smarthome-py/1467710-smarthomeng-mit-mariadb-hängt?p=1467826#post1467826) in knxuf

**Comment by psilo909** [comment]
It could be that this problem passes through the whole core and to different plugins, e.g. database, which is also not multithreaded

**Comment by psilo909** [comment]
Also i think i remember there was a discussion about the performance of highcharts in some cases

**Comment by psilo909** [comment]
i just made a test at my setup:

i opened the page with the "outside temperatures" charts (3 lines, raw values, several charts up to 6 months in the past). in parallel i opened some historic data of the database plugin's webif. while the chart data is being queried in the database, i tried to reload the historic data in the webif. the page reload was stuck until the charts were loaded in smartvisu. so i think the bottleneck is the database is.

i think the only way to solve it would be to "merge" datapoints like the old sqlite plugin did or to generate and use a more performant database scheme. currently all historic data is in one table only. even a multithreaded visu_websocket plugin wont help here much.

**Comment by msinn** [comment]
Cancelation of series is implemented in SmartHomeNG v1.7.2
