### ISSUE TITLE
onwire plugin - warning: Wrong address size

### ISSUE THREAD

**Issue by chester4444** [smarthomeNG/plugins#303]
Hi, i am using aliases in my owfs.conf on my temperature devices in smarthomeNG:
So
`ow_addr: kitchen `
is used instead of
`ow_addr: 28.XXXXXXXXXXXX`

Its clear why I get this warning:
`1-Wire: Wrong address size 'kitchen' for item temp.kitchen`

the following change in the plugin code could fix this:

`        if addr[2] == '.' and len(addr) != 15:`
`self.logger.warning("1-Wire: Wrong address size '{}' for item {}".format(addr, item))`

**Comment by bmxp** [comment]
Could you please give a sample of your owfs.conf?

**Comment by chester4444** [comment]
_/etc/owfs.conf_ contains this line:
`server: alias = /usr/smarthome/items/ow_aliases`

and the file _ow_aliases_ contains something like this:
`28.XXXXXXXXXXXX = kitchen`
`28.XXXXXXXXXXXX = bathroom`

Yes, a switch de-/activating aliases would be fine

**Comment by bmxp** [comment]
I am working to implement that together with other changes. Will you test it when ready?

**Comment by chester4444** [comment]
> Will you test it when ready?

of course

**Comment by bmxp** [comment]
I think we don't need the additional parameter. Getting the dir from owserver and examining ``/settings/alias/list`` we get a list of device id with the corresponding alias. If we start the plugin and read this list, we could check if the definied ow_addr in Items matches one of the sensors listed in the alias list.
Would that be fine for you, too?

**Comment by bmxp** [comment]
First Push. A little bug is still there but will be fixed soon.

**Comment by chester4444** [comment]
looks great, works like a charm, fantastic idea to use the aliases fetched from the owserver.

2 things:

- typo: the switch is called **_use_ow_aliases_**  in the file [plugin.yaml](https://github.com/smarthomeNG/plugins/blob/develop/onewire/plugin.yaml) 
but **_use_ow_alias_** in [README.md](https://github.com/smarthomeNG/plugins/tree/develop/onewire) - but the switch isnt used in the plugin code anyway, right?

- i am using  the DS2438 device with an humidity sensor (HIH-4000) and now I get this warning:
`plugins.onewire.owbase 1-Wire: unknown sensor Feuchte DS2438 page3: b'\x00\x00\x00\x00\x00\x00\x00\x00'` - seems the user memory of my DS2438 should contain something more useful.

**Comment by bmxp** [comment]
use_ow_aliases is already deprecated now :-) I will remove that and as well the part in Readme.md

I will have to look at the sensor thing but am not aware that I changed things there. Will fix this later tonight.

**Comment by bmxp** [comment]
Push done, please test it.

**Comment by chester4444** [comment]
good job, works for me. thanks

And on page 3 of my self-built DS2438/HIH4000 sensor I changed the first byte to 0x19:
fixes this warning: `plugins.onewire.owbase 1-Wire: unknown sensor Feuchte DS2438 page3: b'\x00\x00\x00\x00\x00\x00\x00\x00`
