### ISSUE TITLE
plugin SMA_EM new parsing method with obis-ids:

### ISSUE THREAD

**Issue by Shaq83** [smarthomeNG/plugins#319]
SMA changed the multicast. It is now 608 byte instead of 600 bytes long, see: [http://www.eb-systeme.de/?page_id=3005](url). 

Both the before linked author and [https://github.com/datenschuft/SMA-EM/](url) changed the parser to find measurements based on the obis-ids wich would make the parser future proof.

**Comment by psilo909** [comment]
@Shaq83 I read this but due to my older hardware, i am not able to test the new format with a sma energy meter v2. 

So: Feel free to provide a tested (!) Pull Request with the new code.

**Comment by Shaq83** [comment]
GutenMorgen @psilo909 , unfortunately i am not a coder and unable to change the parsing method. I would be happy to assist with testing and documentation if that helps.

**Comment by psilo909** [comment]
i see what i can do here. the change looks pretty major (intense checks of versions).

in case i get it working with my old energy meter 1.0, i will hardly need some testing from users with other versions

**Comment by psilo909** [comment]
suppose i already have it working, unfortunately they renamed the attributes, e.g. pregard -> pconsume

so the modification of the plugin will be a BREAKING change.

**Comment by psilo909** [comment]
doing good progress... i will provide a struct for the new items

**Comment by psilo909** [comment]
Das Plugin liegt geupdated unter https://github.com/smarthomeNG/plugins/tree/develop/sma_em

Wichtig: Du wirst den aktuellen DEV Core brauchen, da bspw. das Web Interface auf neusten Core Entwicklungen aufbaut.

**Comment by Shaq83** [comment]
Just installed it and it works just fine. Thank you!
