### ISSUE TITLE
All plugins: Update your plugins to enable parameter check by admin interface

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/plugins#345]
Dear plugin developers, maintainers and testers. I have reviewed the plugins available as of April 11th, 2020 and found a bunch of them to not use the latest developments and findings in plugin technology ;-)

It is not needed anymore to pass the plugin parameters to a smart plugins via parameter of init function. It is however good practice to use the ``self.get_parameter_value()`` function instead of passing arguments. This enables the admin interface to configure the plugins during runtime and provide error checking.

Furthermore it is advised to update all meta data. Please revise the section of tester, maintainer and especially the state of development. Is the plugin doing fine the it should be communicated in the plugin.yaml.
Check to see if there is a support thread in knx user forum and please fill in the keywords as well.
Did you also check for a logo to use in gui and webinterface?

# Plugins (that are not deprecated) to overhaul:

- [ ] plugins/comfoair/__init__.py            # Stefan Kals
- [ ] plugins/helios/__init__.py              # Tom-Bom-badil
- [ ] plugins/intercom_2n/__init__.py         # @pfischi
- [ ] plugins/jvcproj/__init__.py             # Nico P.
- [ ] plugins/kostal/__init__.py              # @ohinckel, Wenger Florian
- [ ] plugins/luxtronic2/__init__.py
- [ ] plugins/plex/__init__.py                # @rthill 
- [ ] plugins/rcswitch/__init__.py            # Daniel Frank
- [ ] plugins/roomba_980/__init__.py
- [ ] plugins/sma/__init__.py                 # @robert-budde 
- [ ] plugins/smarttv/__init__.py
- [ ] plugins/sml/__init__.py                 # @ohinckel
- [ ] plugins/systemair/__init__.py           # @robert-budde

**Comment by msinn** [comment]
The Issue title is a bit misleading. parameters are checked though lib.metadata and this is done even if ``self.get_parameter_value()`` is not used. The Admin Interface uses only the metadata from plugin.yaml to check entered config data.

The list above seems to reflect only, if get_parameter_value() is used in the plugin.

**Comment by msinn** [comment]
Almost nothing happens with this issue. In the last year from the to to list only two plugins have been modified, one was retired and one was deprecated. 

I moved the plugins to the appropriate sections of the first post.

**Comment by Morg42** [comment]
checked and modified some plugins in PR #857 

As I can't test any of those plugins, please test them if you can - @maintainers?

**Comment by Morg42** [comment]
All listed plugins are checked and modified, please test.

**Comment by Morg42** [comment]
addendum: i "migrated" all plugins to the SmartPlugin call syntax of init, tried to make them restartable, moved scheduler calls from sh to SmartPlugin, removed superfluous logging imports and cleaned up the code a bit (visually mostly, to (mostly) comply with PEP8 (e.g. for flake8).

As I do not own any of the devices, I can not really test the plugins short of "run up to unfinished init"...

**Comment by Morg42** [comment]
As the PR is merged, this seems to be done.
