### ISSUE TITLE
Pluggit Plugin - Update Parameters in ini

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/plugins#369]
See https://knx-user-forum.de/forum/supportforen/smarthome-py/838373-neues-plugin-f%C3%BCr-kwl-pluggit-ap310/page2#post1502236 for details.

**Comment by msinn** [comment]
Hi Bernd,
the forum software displays the first post on page two of this thread when clicking your link, which is from 2015. Seaching for 'parameter' on that page yields no result that would give me any indication what this issue is all about.

**Comment by bmxp** [comment]
This issue indicates that there are errors that have been already fixed by @cannon but they need to be inserted into the plugin code like

```
'prmRamIdxRh3Corrected': 196, # 40197: Luftfeuchte
'prmVOC': 430, # 40431: VOC sensor value (read from VOC); ppm. If VOC is not installed, then 0.
```

In the meantime user @cannon started a revision of the whole plugin so the issue might be obsolete anyway.

**Comment by msinn** [comment]
@bmxp Do you have an update for this issue?

**Comment by bmxp** [comment]
Unfortunately not. @cannon any news on this Problem?

**Comment by cannon** [comment]
no

**Comment by bmxp** [comment]
Ok, I've included your fixes from https://knx-user-forum.de/forum/supportforen/smarthome-py/838373?p=1502259 to the current plugin in public repo. Looking forward for your brandnew plugin then later :-)
BTW: Happy New Year!
