### ISSUE TITLE
Convert ancient Plugins to use lib.network instead of lib.connection

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/plugins#399]
Currently the following plugins still use ``lib.connection`` but are deprecated and will be removed:

* raumfeld  (deprecated)
* visu_websocket  is deprecated and a module as replacement is in place @develop branch

The following plugins already have an implementation:
- [x] cli
- [x] knx
- [x] lirc (thanks to @onkelandy )
- [x] nuki (thanks to @psilo909?)
- [x] squeezebox (thanks to @onkelandy)

These plugins were converted by @Morg42 but are not pushed into develop:
- [x] network (thanks to @Morg42, Test: Tom Bombadil, OnkelAndy)
- [x] asterisk (thanks to @Morg42, test by @sisamiwe?)
- [x] mpd (thanks to @Morg42)
- [x] russound (thanks to @Morg42)
- [x] speech (thanks to @Morg42)

The ``lib.connection`` should then be removed prior to SmartHomeNG 2.0

**Comment by onkelandy** [comment]
Umgebaute Squeezebox und lirc funktionieren bei mit seit Wochen ohne Probleme.

**Comment by Morg42** [comment]
Plugin network is finished and runs completely on lib.network.
Plugin cli is adapted and will be provided together with the new lib.network.
Plugins lirc, knx, squeezebox don't need updates and work out of the box.

**Comment by Morg42** [comment]
All modified and awaiting testing in https://github.com/Morg42/plugins/tree/network/, necessary lib.network in https://github.com/Morg42/smarthome/tree/libnetwork/

**Comment by bmxp** [comment]
Maybe we should wait until the next release 1.8 which is prepared by @msinn for January 
until the efforts of @Morg42 are pushed into develop?
This way we can get a more thorough test in develop instead of pulling from the private repo.

**Comment by Morg42** [comment]
That was my suggestion to @msinn already. Much as I'd like to see lib.network in 1.8, more testing and completion of plugin seems sensible.

**Comment by msinn** [comment]
That's why I added the milestone 1.9 before your comments.

**Comment by Morg42** [comment]
All lib and plugin code is integrated and running. References to lib.connection are removed in plugins; for core files, this is provided in PR smarthome/#402.

The last remaining point is actually removing lib.connection from the core.

This should probably be done earliest for 1.10, so privately used plugins can be adjusted.

Does this need some kind of deprecated-warning?

**Comment by bmxp** [comment]
Yes, we should give a warning with each usage of lib.connection IMHO. @msinn did a great job with other deprecated warnings within the code.
The only fear I have is that some users won't get the deprecated warning due to misconfigured logging setup.

**Comment by Morg42** [comment]
The warning "system" might be upgraded to show a all-pages warning on the Admin UI.

On the other hand, we can't make sure to reach everyone. A best-effort approach should be enough on evolving OSS. As long as some users don't update their systems, nothing is going to happen anyway. I guess you can expect someone upgrading to read the release notes, or the readme?

**Comment by bmxp** [comment]
If I've learned anything important in my life then the most important lesson is the one that people don't read anything until something goes wrong. And if this is the case, then they blame the docu that it was not presented in an understandable way.
Most people would easily sign their own death warrant ...

**Comment by Morg42** [comment]
I'm painfully aware. But not doing anything is not an option...

**Comment by Morg42** [comment]
Closing this issue as the plugin modification is complete.

The core issue is resumed at [issue 410 @smarthome](https://github.com/smarthomeNG/smarthome/issues/410)
