### ISSUE TITLE
smartvisu: Feature request for plugin specific widgets (icon style)

### ISSUE THREAD

**Issue by wvhn** [smarthomeNG/plugins#518]
Plugin specific smartVISU widgets are often delivered only with white svg icons. The docu says that icons will be copied from the plugins „sv_widgets“ directory to smartVISU „dropins/icons/ws“.
These icons can not be used with smartVISU designs requiring black icons (e.g „ice“).
In addition to the current behavior, the smartvisu Plugin should check whether an „icons“ folder exists inside „sv_widgets“ and then copy the contents from the subdirectories „ws“ and „sw“ into smartVISU  „dropins/icons/ws“ and „ dropins/icons/sw“.

**Comment by msinn** [comment]
Feature implemented. Will be included in the next release

**Comment by msinn** [comment]
SmartHomeNG v1.9.2 with the resolution has been released
