### ISSUE TITLE
hue2: Add bridge not working with newer versions of qhue

### ISSUE THREAD

**Issue by CaeruleusAqua** [smarthomeNG/plugins#527]

**Comment by CaeruleusAqua** [comment]
` def create_new_username(self, ip, port, devicetype=None, timeout=5):`

failes because:

` res = qhue.qhue.Resource(api_url, timeout)`

needs session object:

` res = qhue.qhue.Resource(api_url, requests.Session(), timeout)
`

**Comment by Morg42** [comment]
Works for me.

Close issue?

**Comment by msinn** [comment]
I close the issues that are marked as resolved, when the next release is out.
(Otherwise someone could open an issue, since he has still problems with the master branch

**Comment by msinn** [comment]
Version 1.9.0 is released
