### ISSUE TITLE
database: Handling of removal of large number of old records

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/plugins#547]
database plugin creates  a new thread to remove old entries in items marked with ``database_maxage`` attribute. This happens every 91 seconds currently. Unfortunately several threads are startet one after the other even the first thread did not finish. 

This results in a huge number of threads if some more items are marked with the database_maxage attribute before a restart of SHNG

**Comment by bmxp** [comment]
This was adressed as of release 1.9.3. 
A parameter can be configured to declare the approximate maximum logentries that should be deleted at once.

Please test and report if there still occur problems.

**Comment by msinn** [comment]
@bxmp You raised this issue and told to yourself last November that it was fixed and you should test it. :smile:
Could you answer yourself? :wink:

**Comment by bmxp** [comment]
I think this issue can be closed as we have fixed several things recently.
