### ISSUE TITLE
avm: still getting 404s from Wifi Repeaters

### ISSUE THREAD

**Issue by psilo909** [smarthomeNG/plugins#583]
For the AHA stuff, the plugin also seems to request the AHA webpage on my repeaters. Unfortunately, Repeaters done have AHA web page.
Thats why a 404 is returned.

We need a possibility to somehow exclude these devices or to not log the 404.

2022-02-16  19:27:38 ERROR    plugins.avm      wlan_repeater_2400_garage@: AHA command error code: 404
2022-02-16  19:27:38 ERROR    plugins.avm      wlan_repeater_1750_galerie@: AHA command error code: 404
2022-02-16  19:27:39 ERROR    plugins.avm      wlan_repeater_1750_front@: AHA command error code: 404

**Comment by psilo909** [comment]
Interestingly Ihave 4 Wifi repeaters (one more in Garage), but i am getting this only for 3

**Comment by sisamiwe** [comment]
As mentioned I will try to solve the remaining issues. Also I have found some other bugs, which where not detected yet. 
Nevertheless I will work in an further improved version. Help is appreciated!

**Comment by sisamiwe** [comment]
> _update_aha_devices

The "self._update_aha_devices()" should be run once per update loop without any if condition. 
The update mechanism between TR-064 and AHA is different: 

- For TR-064 the update is run via item, means item with avm attribute triggers a method to get dedicated value for the reqested item. 
- For AVA, all avalailable data a called at once (via _get_aha_device_elements) an put to an internal dict (via _update_aha_devices). The update of the items itself is a second step (via _update_smarthome_items). Here we iterate over smarthome items and look for matching information in dict, we created a step before. This cylce is started with  "self._update_aha_devices()"

**Comment by sisamiwe** [comment]
A fix has been developed . It is published here. https://github.com/sisamiwe/shng-avm-plugin
Please test it. After I got the OK, I will do an PR with some fixes.

**Comment by aschwith** [comment]
Looks good!

**Comment by sisamiwe** [comment]
Issue should be solved in develop
Please check and close issue if so

**Comment by aschwith** [comment]
Issue gas been resolved. Closing this one.
