### ISSUE TITLE
homematic: error 500 module website

### ISSUE THREAD

**Issue by laraveluser** [smarthomeNG/plugins#585]
Hi,
I get an error 500 when I open the Homematic module website. Possibly because I have partially named my items, "str(item)" does not work here:
https://github.com/smarthomeNG/plugins/blob/e32b0ef38791667c903e9ffe0c7e88f32a5ba59c/homematic/__init__.py#L238
If you replace this with str(item.property.path), it works again without problems:

    self.hm_items.append( [str(item.property.path), item, hm_address, hm_channel, hm_function, hm_node, dev_type] )

It would be nice if you could change this in later updates.
Thank you in advance

**Comment by msinn** [comment]
@laraveluser What do you mean by "Homematic module website"? Do you mean the Homematic CCU web interface?

**Comment by laraveluser** [comment]
Ave,
vielleicht kann ich mich in Englisch nicht so klar ausdrücken. Ich vermute mal, du verstehst auch deutsch. 
Ich meine das Plugin-Interface in der Admin-Ansicht. Mir ist das Problem aufgefallen, als ich neue Geräte hinzufügen wollte und deren Parameter im Webinterface auslesen wollte. Hier wurde nur Fehler 500 ausgeworfen. Sobald ich das wie oben beschrieben geändert hatte, funktionierte die Plugin-Seite wieder normal. 
vG

**Comment by laraveluser** [comment]
Die HM-Items werden nach definierten Namen - soweit vorhanden - oder Pfad abgelegt. Die Sortierfunktion von Python hat anscheinend ein Problem, wenn mehrere Elemente den exakt gleichen Namen tragen. Es macht aus meiner Sicht durchaus Sinn mehrere Items gleich zu benennen, wenn sie unterschiedliche Funktionen haben. Insoweit ist das vlt. ein Gedankenanstoß für die zukünftige Entwicklung. Für meine Anwendung ist das Problem jedenfalls erstmal behoben.

Renaming items with the same name solves the problem in any case.
