### ISSUE TITLE
mqtt plugin: Headlines missing in plugin webif's datatables

### ISSUE THREAD

**Issue by aschwith** [smarthomeNG/plugins#608]
In plugin version mqtt v2.0.2 (smarthomeNG release V 1.9.2) headlines are missing in all datatables of the plugin's webinterface.

**Comment by msinn** [comment]
What do you mean by „all datatables“?

The only table in the web interface i have, is in tne **mqtt items** tab and this table shows headings in my installation.

**Comment by aschwith** [comment]
Cannot be reproduced. Probably a false alarm due to a caching problem on my side. Closing this one.
