### ISSUE TITLE
husky2: Plugin 'automower' error importing Python package: No module named 'homeassistant'

### ISSUE THREAD

**Issue by lgb-this** [smarthomeNG/plugins#610]
I install smarthomeng new and enabled the plugin husky2. I found these 2 lines in the log:

2022-05-28  07:40:00 ERROR    lib.plugin          Plugin 'automower' error importing Python package: No module named 'homeassistant'
2022-05-28  07:40:00 ERROR    lib.plugin          Plugin 'automower' initialization failed, plugin not loaded

It seems, that the module 'homeassistant' is not in the file requirements.txt included.

**Comment by bmxp** [comment]
Homeassistant is not used but an exception from homeassistant introduced in ``aioautomower/rest,py`` found ``from homeassistant.exceptions import ConfigEntryAuthFailed``

Maybe this should be fixed in the [aiomower module](https://github.com/Thomas55555/aioautomower/blob/main/aioautomower/rest.py).

**Comment by lgb-this** [comment]
Ok, thanks for the hint. I installed the module manually.
