### ISSUE TITLE
UZSU Plugin: issue with plugin version in dict

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/plugins#627]
Version only gets written in some cases in the run method. Should be integrated in the parse_item method to make sure it's in there in all UZSU dicts.

**Comment by bmxp** [comment]
Did you have any findings that made it into Release 1.9.3?

**Comment by onkelandy** [comment]
should be fixed indeed. https://github.com/smarthomeNG/plugins/pull/634/commits/864509b33c1f1c57b6e7c87865be6f52f531d2a6
