### ISSUE TITLE
svNG Plugin join: Missing "say" and "language" commands

### ISSUE THREAD

**Issue by jksd** [smarthomeNG/plugins#673]
Hello,
am just switching from fhem to svNG and have been using join's say function to do voice output from svNG to my android panels via tts. When I went live, I found that the join plugin didn't support "say" and specifying the local language "language".

It would be nice if someone with access to the repo could add the parameters "say" and "language" to the plugin in __init__.py in the method "send()" as follows:

<code>
def send(self, title=None, text=None, icon=None, find=None, smallicon=None, device_id=None, device_ids=None,
             device_names=None, url=None, image=None, sound=None, group=None, clipboard=None, file=None,
             callnumber=None, smsnumber=None, smstext=None, mmsfile=None, wallpaper=None, lockWallpaper=None,
             interruptionFilter=None, mediaVolume=None, ringVolume=None, alarmVolume=None, say=None, language=None):
</code>

and

<code>
        if say:
            req_url += "&say=" + say
        if language:
            req_url += "&language=" + language
</code>

Thank you in advance,
Jörk

**Comment by aschwith** [comment]
Added say and language options as you suggested to plugin version 1.4.3 on the develop branch. Please doublecheck, test and report back, whether this issue can be closed.

**Comment by jksd** [comment]
Hi,

thank you very much. I just did a quick test and it works fine.

Best regards,
Jörk

**Comment by aschwith** [comment]
All right. Closing this one.
