### ISSUE TITLE
svNG plugin harmony: PowerOff handling not correct

### ISSUE THREAD

**Issue by jksd** [smarthomeNG/plugins#674]
Hello,
I am just switching from fhem to svNG and today I had analysed my problem that current_activity_id and current_activity_name are only updated with a time delay after approx. 3 minutes after switching off. With all other activities this happened immediately.

I found the problem in __init__.py and fixed it.

<code>
 def _message(self, message):
        self._logger.debug("Harmony: message: {msg}".format(msg=message))
        # we have to check two response due to some version changes in harmony device
        # ORIGINAL # match = re.match(r".*?startActivityFinished\">activityId=(\d+):errorCode=200.*",
        # NEU #
        match = re.match(r".*?startActivityFinished\">activityId=(-?\d+):errorCode=200.*", html.unescape(str(message)))
        if not match:
            # ORIGINAL # match = re.match(r".*?startActivityFinished\">errorCode=200:errorString=OK:activityId=(-?\d+)",
            # NEU #
            match = re.match(r".*?startActivityFinished\">errorCode=200:errorString=OK:activityId=(-?\d+)", html.unescape(str(message)))
        if match:
            self._set_current_activity(int(match.group(1)))
</code>

The RE wasn't correct. The "Minus sign" was missing before (PowerOff = activity -1). So, PowerOff was only recognized with following polling cycle (assumption). 

Please check in to the repo. Thank you in advance.

Best regards,
Jörk

**Comment by msinn** [comment]
Probably a copy-and-paste mistake in your issue message: The secont ORIGINAL and NEU strings are identical.

I have fixed it in the develop branch.


Btw: The abbreviation should be snNG (for SmartHomeNG) and not svNG.

**Comment by msinn** [comment]
SmartHomeNG v1.9.4 has been released
