### ISSUE TITLE
telegram: Plugin should be improved to use async

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/plugins#708]
The telegram plugin uses threads currently. As the underlying telegram lib will only be improved at async being version > 20.x we should consider a move to async and use newer lib then.

**Comment by ivan73** [comment]
Maybe someone can take a look before I make the pull request?
https://github.com/ivan73/plugins/blob/develop/telegram/__init__.py

**Comment by bmxp** [comment]
The code was merged into develop back in April and since tested successfully together with some enhancements.
