### ISSUE TITLE
database: Plugin does not work with mysql when using a password that starts with numbers

### ISSUE THREAD

**Issue by lexxmm** [smarthomeNG/plugins#806]
database plugin does not work when using a password (database password) that starts with numbers. error occurs with mysql and mariadb

Error: Database: Initialization failed: object supporting the buffer API required

**Comment by msinn** [comment]
@psilo909 Du nutzt doch mysql. Kennst Du dieses Verhalten/Problem?

**Comment by psilo909** [comment]
@msinn nein, habe aber auch kein solches Passwort. Kann's erst ab dem 9.9. nachtesten. Bin noch in USA.

**Comment by Morg42** [comment]
Ist gefixt, lib.db musste an OrderedDicts angepasst werden und Werte ausdrücklich als str übergeben.

Achtung: der Fix ist im Core, nicht in Plugins!
