### ISSUE TITLE
rtr: Plugin might have issue with newest core changes? Deprecated anyhow?

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/plugins#819]
I was wondering if rtr should be labeld deprecated as there is a rtr2?
Furthermore, I guess 
def valve_protect(self, y=100):
needs to be changed to
def valve_protect(self, y=100, caller=None):

to work with latest caller changes in core. Can't test..

**Comment by msinn** [comment]
> I was wondering if rtr should be labeld deprecated as there is a rtr2?

the rtr2 plugin is no update to the rtr plugin. Eache of the two plugins could be used, based on the requirements of the user.

> def valve_protect(self, y=100, caller=None):

Why should that be necessary?

**Comment by onkelandy** [comment]
With the recent scheduler changes this most likely won't be necessary. When I wrote the issue without that change it didn't work. If anyone can test successfully feel free to close this issue.
