### ISSUE TITLE
db_addon: Duplicate values for verbrauch_heute_minus3 and verbrauch_heute_minus2

### ISSUE THREAD

**Issue by stephan-schuster** [smarthomeNG/plugins#835]
There's an error in the struct definition in plugin.yaml, that leads to identical values for "verbrauch_gestern_minus2" and "verbrauch_gestern_minus3", because they both use "verbrauch_heute_minus3" in "db_addon_fct" parameter:

![grafik](https://github.com/smarthomeNG/plugins/assets/68235511/44fcc22d-e251-4d18-85ac-aad85bbf4892)

![grafik](https://github.com/smarthomeNG/plugins/assets/68235511/558ec0d3-567f-4ea4-8a06-9b056786cc5e)

**Comment by onkelandy** [comment]
You could test the newest version here: https://github.com/sisamiwe/plugins/tree/dev-db_addon
All issues should be fixed there (using cache values on startup not implemented yet). Does it work? Please also test the WebIF

**Comment by onkelandy** [comment]
@sisamiwe maintains the plugin. I don't think there was a breaking change but I can't tell exactly. The calculation of the respective entries should take some minutes after start of shng - at least for those entries that have "run on init" active. Other values might be evaluated at the start of a month but you can manually start the process using the buttons. However, I think there is a newer version of the web interface available (somewhere.. ;))
Not sure if in a previous version all older values such as monat_minus2 was calculated on start up..??

For sure the values should be saved for re-use on the next startup, this is in progress already (using internal cache or cache in the plugin structs)

**Comment by sisamiwe** [comment]
@stephan-schuster 
@onkelandy 

Hey, 
there should be no breaking changes using the newest version here: https://github.com/sisamiwe/plugins/tree/dev-db_addon

There are some new attributes, replacing some old one to make the naming more stringend, but the old one works as well. I've replaced the attributes in the structs as well. This is a change, of course.

The thing I changed is to remove the cache attribute from the items in struct. Thats why there are no values direct after restart of shNG. They appear as they are calculated, which might take some minutes. You can check in the AdminIF for the items itself or within the stucts, of the attribute für calculating at startup is given.

I'm still struggeling, whether using the shNG interal cache for making values surviving a restart usefull. The cached values might be updated already. On the other hand, this is also valid for all other cached values.
Probably I will just put the cache attribute back to the structs.

BTW: The structs are already corrected so the the right values will be calculated.

**Comment by sisamiwe** [comment]
> @sisamiwe thanks for your support. With \"breaking changes\" I meant the renaming of the item names / addon attributes, but that's no problem to change them.

Hey,
Do you have an account on gitter?
That would eas the communication.

**Comment by stephan-schuster** [comment]
@sisamiwe
> Do you have an account on gitter?

Now I have :-)

**Comment by stephan-schuster** [comment]
@sisamiwe
Another suggestion: values for a period like verbrauch_tag (verbrauch_woche, verbrauch_monat) that are calculated on change should be reset to zeo at the beginning of the day (week, year). Otherwise they show the value of yesterday (last week, last year) when no change occurs.

**Comment by onkelandy** [comment]
Can this issue be deleted @sisamiwe ?

**Comment by sisamiwe** [comment]
> Can this issue be deleted @sisamiwe ?

Yes, issue solved with current release in develop
