### ISSUE TITLE
influxdb, influxdb2: Add database data retrospectively

### ISSUE THREAD

**Issue by gruberth** [smarthomeNG/plugins#845]
It would be really helpful if you could add a function to retrospectively transfer the "old" data from items stored in the database plugin to the Influx database through the web interface.
Maby you could name this feature "manual transfer". It checks the data entries in the database plugin and adds the missing entries to the Influx database.

Thanks

**Comment by msinn** [comment]
I think that this feature should be implemented in a tool outside the plugins.

**Comment by gruberth** [comment]
I did it with the following python script using `pandas` and `influxdb_client`.

If someone else needs this, follow these steps:
1. Download the CSV dump form the database plugin webinterface
2. Edit the access parameter in the script to match your influxdatabase
3. Edit the path to the CVS file
4. Run the Script
5. Depending on the size of the database waaaaaait for hours



```
from influxdb_client import InfluxDBClient
from influxdb_client.client.write_api import SYNCHRONOUS
import pandas as pd


# ----------------------------------------------
ip = "localhost"
port = 8086
token = "******************"
org = "smarthomeng"
bucket = "shng"
value_field = "value"
str_value_field = "str_value"

csvfile = "smarthomeng_dump.csv"
# ----------------------------------------------


client = InfluxDBClient(url=f"http://{ip}:{port}", token=token, org=org)
write_api = client.write_api(write_options=SYNCHRONOUS)

df = pd.read_csv(csvfile, sep=';', header=0)
df = df.reset_index()

num_rows = len(df.index)
last_progress_percent = -1

for index, row in df.iterrows():
    progress_percent = int((index/num_rows)*100)
    if last_progress_percent != progress_percent:
        print(f"{progress_percent}%")
        last_progress_percent = progress_percent

    p = {'measurement': row['item_name'], 'time': int(row['time']) * 1000000,
         'tags': {'item': row['item_name']},
         'fields': {value_field: row['val_num'], str_value_field: row['val_str']}
         }
    write_api.write(bucket=bucket, record=p)

client.close()

```

**Comment by onkelandy** [comment]
Thanks for the nice solution. I've included the info in the docu: https://github.com/smarthomeNG/plugins/pull/850

**Comment by gruberth** [comment]
Btw. @onkelandy  I used this script for the influxdb2 plugin and an influx V2 database. I am not sure if the login via token is also possible for the V1 database.
