### ISSUE TITLE
sml2 Plugin hat keine auto reconnect Funktion

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/plugins#861]
Es wäre wünschenswert wenn das SML2 PLugin eine automatische reconnect Funktion besitzen würde. Ich habe einen Lepus Zähler der wohl gerne mal die Serielle Verbindung nicht bedient und dann schliesst sich das Plugin. Das ist natürlich etwas blöd...

**Comment by Morg42** [comment]
Ich habe im smartmeter-Plugin mal die async-Funktionalität eingebaut, aber das läuft mit meinem DLMS-Simulator nicht, und da passiert so viel "hinter den Zäunen" von serial_asyncio, dass ich noch nicht ganz durchsehe, wie ich die Verbindung 1. gezielt trennen kann und 2. wie ich sie wieder gezielt aufbauen kann. Die on_disconnect-Methode wäre ja vorhanden.

Wenn ich a) etwas mehr Ruhe und b) eine Möglichkeit habe, DLMS live zu testen, gehe ich da ran ;) (dann aber nicht mehr für sml2, sondern für smartmeter)

**Comment by Morg42** [comment]
Ich bin so frei und schließe das hier; wenn jemand sich an sml2 nochmal verlustigen möchte, dann mache ich das auch wieder auf.
Ansonsten im Entwicklungszweig smartmeter
