### ISSUE TITLE
db_addon: sometimes values aren't recalculated

### ISSUE THREAD

**Issue by stephan-schuster** [smarthomeNG/plugins#904]
First of all I would like to thank you for this great plugin, it has saved me a lot of time. But there is still a small problem: Sometimes the values are not recalculated and remain at 0:

![grafik](https://github.com/smarthomeNG/plugins/assets/68235511/5b6a77ad-c121-4a90-a5a7-3849564c826d)

The picture is taken on a tuesday at 14:35, so the values for the current week / day can't be 0. And after triggering the recalculation in the web interface the values are shown. So the plugin seems to have problems to determin, which values have to be recalculated.

**Comment by sisamiwe** [comment]
Diverse methods and functions have been rewritten to solve this bug.
During tests on my side, it never accurred again.'
@stephan-schuster please test the pr

**Comment by stephan-schuster** [comment]
thanks for reaching out again, I've had installed 1.2.7 version that had other problems. The values for current day / week / month didn't show up 0 anymore, but calculated the values from day 0:

![grafik](https://github.com/user-attachments/assets/9c8d05c9-0cf8-4e15-8e2e-b35649cba91d)

After recalculation in the admin the values were correct:

![grafik](https://github.com/user-attachments/assets/210bb108-a1fe-40a7-8cd6-474fc4581816)

But after some time it always switched back to the wrong values. When I tried to use version 1.2.10 from your PR, the plugin could not be initialized:

```
2024-12-08  16:16:54 ERROR    lib.metadata        plugin 'db_addon' v1.2.10: The Python version v3.8.10 is too old for this plugin. It requires at least version v3.9.0. The plugin was not loaded.
```
I tried to do a release upgrade of the underlying Ubuntu 20 to 22 to get a newer python version, but this resulted in several other errors and a completely disfunctional smarthomeng, so I had to restore the snapshot that I've created before.

Is it possible to use this plugin with python v.3.8?

**Comment by sisamiwe** [comment]
Within the PR there is 1.2.10.
I dont know it the plugin runs with python 3.8. I've not testet it.
you could change the min_py_version in plugin.yaml and give it a try

**Comment by stephan-schuster** [comment]
ok, I've adjusted the version. Now I'm getting lots of errors about a missing _pause_item attribute:

```
AttributeError: 'DatabaseAddOn' object has no attribute '_pause_item'
2024-12-08  18:18:33 ERROR    lib.item.item       Item PvAnlage.grid: problem running <bound method DatabaseAddOn.update_item of <plugins.db_addon.DatabaseAddOn object at 0x7fe4c40e6d00>>: 'DatabaseAddOn' object has no attribute '_pause_item'
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/item/item.py", line 2265, in __update
    method(self, caller, source, dest)
  File "/usr/local/smarthome/plugins/db_addon/__init__.py", line 755, in update_item
    if item is self._pause_item:
```
I've tried to use an empty value in my etc/plugin.yaml, but same result. I've no idea, what should I enter in this config value?

**Comment by sisamiwe** [comment]
That error is not caused by the python version, but from min shNG version.
@Morg42 
Could you help out?

**Comment by stephan-schuster** [comment]
@sisamiwe sure? I'm using shNG v.1.10.

Looks to me, like a missing configuration parameter:

```
        # define default mysql settings
        self.default_connect_timeout = 60
        self.default_net_read_timeout = 60

        # define variables from plugin parameters
        self._pause_item_path = self.get_parameter_value('pause_item')
        self.db_configname = self.get_parameter_value('database_plugin_config')
```
But I don't know, what to enter here...

**Comment by sisamiwe** [comment]
I'm sure. You need shNG 1.10.0.3 (which is the current develop).

You can try to comment the _pause_item stuff out.

**Comment by stephan-schuster** [comment]
@sisamiwe ok, I've commented it out an now it seems to work. After recalculation the values seem plausible. I'll keep an eye on it and will report if I'm facing problems again. Thanks for the great support
