### ISSUE TITLE
database: Wrong return value for item.db() function for sparsely filled databases

### ISSUE THREAD

**Issue by aschwith** [smarthomeNG/plugins#906]
### Description: 
The database function .db() returns wrong values for sparsely filled database, if no valid values are inside the requested time interval.

### Steps to reproduce: 
1. Configure item with attribute database: yes
2. Fill database with a couple of values between time t1 and t2, e.g. one value per day
3. Stop adding values for at least one day
4. Now execute logic database function, e.g. calc minimum value, for a time interval between now and the last 12 hours:
    -> item.db('min', '12i', 'now')

### Issue:
Function returns the last value in the db, even though the value is not inside the requested interval.

### Expected behaviour: 
Function returns None if no db entries are available inside the requested interval

**Comment by wvhn** [comment]
I don‘t think it‘s a bug. This is more due to the test conditions.

The last dataset in the database always has the duration null. So if you just stop sending data to the database the last value is considered to be valid until now and hence is in the requested interval. You would have to write a duration to the last dataset while stopping the data storage in order to make the last dataset fall outside the requested interval.

**Comment by aschwith** [comment]
Maybe this explains the current behavior. However, it is not consistent. Let's assume two different cases of a slightly different scenario, where t_end is not equal to 'now', e.g. calculate the minimum value of all values in a 12 hour interval being defined in the range 36hours ago until 24hours ago:  item.db('min', '36i', '24i')
a) First example
No update during the requested interval described above. This means no db entries in this interval. Let's further assume, there is a db entry OUTSIDE and AFTER the interval.
-> item.db('min', '36i', '24i') will simply return the last entry in the database, even though it is outside therequested interval. 

b) Second example: Let's assume there are two values INSIDE the requested interval and again the same third value OUTSIDE the interval as in a)
-> item.db('min', '36i', '24i') will then calculate the minimum of the two values INSIDE the interval and not even consider the third db entry OURSIDE the interval. 

My point is that the use of the DB entries OUTSIDE the interval is not consistent. In a) it is used, in b) it is not used. 

Another con argument is that with this behavior, we loose the possibility to determine whether there are values inside the requested interval or not.

**Comment by wvhn** [comment]
When testing the scenarios,  be aware that „i“ is the duration unit for minutes. Hours is „h“. Maybe this is the cause for the misunderstanding. 

In scenario a), the item value *during* the requested interval must be equal to the last database entry value *before* the interval. In my test, the database delivers this value correctly.

in scenario b) my test delivers the minimum of both values inside the interval correctly. Here, the last value inside the interval will be valid until the next update which is outside the interval. So no need to consider the outside value.

**Comment by aschwith** [comment]
You are completely right. I ran both of your outlined examples and they work as expected. My fault was to assume that no db entry within a certain interval always should lead to a return value None. In fact this is only true if there was never a db entry before. Once you add a db entry, it can never be invalidated again. Therefore, every db request from this point on, will at least consider this entry. 
To conclude, you are correct. Works as designed. I will close this issue.
